# config_pyiot.yaml
# IoT Configuration
config_iot:
  mqtt:
    server_url: "broker.mqttdashboard.com"        # http://www.hivemq.com/demos/websocket-client/
    server_port: 1883
    topic_sub: "/eyrc/vb/BiAdKaHa/orders"          # <unique_id> = BiAdKaHa
    topic_pub: "eyrc/BiAdKaHa/ros_to_iot"          # <unique_id> = BiAdKaHa
    qos: 0

    sub_cb_ros_topic: "/ros_iot_bridge/mqtt/sub"   # ROS nodes can listen to this topic to receive data from MQTT
  google_apps:
    spread_sheet_id: AKfycbxZjLKDKs_WZ6DHznHcRSnoy2_bh68jGCpYCY4dtaQXAVcoszN8VL4_
    submission_spread_sheet_id: AKfycbw5xylppoda-8HPjt2Tzq4ShU_Xef-Ik-hEtBPcPk0gdGw8095j4RZ7
