# config_pyiot.yaml 
# IoT Configuration
config_iot:
  mqtt:
    server_url: "broker.mqttdashboard.com"        # http://www.hivemq.com/demos/websocket-client/
    server_port: 1883
    topic_sub: "eyrc/BiAdKaHa/iot_to_ros"          # <unique_id> = xYzqLm
    topic_pub: "eyrc/BiAdKaHa/ros_to_iot"          # <unique_id> = BiAdKaHa
    qos: 0

    sub_cb_ros_topic: "/ros_iot_bridge/mqtt/sub"   # ROS nodes can listen to this topic to receive data from MQTT
  google_apps:
    spread_sheet_id: AKfycbyCP1sSuhhpKHozn5suvUhGh-7k4lxbGGWKEF4K7ox8cJSJfKE
